version: '3.9'
services:
  db:
    image: mysql:8.0.23
    container_name: delivery-app-dev
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'
